#!/usr/bin/env python3
print()
print ('<html>')
print ('<head>')
print ('<title>Hello Word - First CGI Program</title>')
print ('</head>')
print ('<body>')
print ('<h2>insert an inspirational quote here</h2>')
print ('</body>')
print ('</html>')